core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import index, contact

urlpatterns = [
    # all the @name we put here will make it easier to reference later
    path('', index, name='index'),
    path('items/', include('item.urls')),
    path('contact/', contact, name='contact'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

item/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
# For categories
class Category(models.Model):
    name = models.CharField(max_length=255)

    # To change categorys to Categories
    # When we want to order by name its done inside the Meta. Which is like options configuration for the model
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    #This is to show the names of their ctegories themselves i.e instead of Category object (3) to Toys
    def __str__(self):
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    #null = True in case the user dowsnt wanna provide the description
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    # If the user is deleted all item created by the user will be deleted
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

core/views.py
from django.shortcuts import render

from item.models import Category, Item

# Create your views here.
# This info about the browser. If you gonna Post or Get
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

item/views.py
from django.shortcuts import render, get_object_or_404

from .models import Item

# Create your views here.
def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })

core/templates/core/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <!-- This will ensure that the browser can interpret and display the text correctly, regardless of the language or script used.-->
        <meta charset="utf-8">
        <!--This is to make the website mobile friendly-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--So we can use Tailwind CSS-->
        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Puddle</title>

    </head>

    <body>
        <!--The <nav> element is a specific container that represents a navigation menu. This Tailwind class-->
            <!--The result is that the content inside these elements will have a 1.5rem gap from the border on all sides.In simple its padding for navigation menu-->
            <!--@justify-between to make sure text is between logo and the links. @flex we want it to be next to each other -->
            <!--@items-center so that the links same height to be the same as the logo. @border-b its for border in the bottom-->
            <nav class="py-6 px-6 flex justify-between items-center border-b border-grey-200">

                <!--We want the logo in the left-->
                <a href="/" class="text-xl font-semibold">Puddle</a>

                <!--Items next to the logo. @space-x-6 is for space for each items put there-->
                <div class="space-x-6">
                    <a heref="#" class="text-lg font-semibold hover:text-gray-500">New item</a>
                    <a heref="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                    <!--@bg-teal means background must be teal a dark green color. @rounded-xl to get the corners rounded-->
                    <a href="#" class="px-6 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="#" class="px-6 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                </div>
            </nav>

        <!--Tailwind class for padding-->
        <div class="px-6 py-6">
            {% block body %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">

            <!--@w-2/3 Means take 2/3 of the footer. @pr-10 means padding right set to 10-->
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Lorem ipsum bla bla bla, Lorem ipsum bla bla bla, Lorem ipsum bla bla bla,</p>

            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms Of Use</a></li>
                    
                </ul>
            </div>

        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends "core/base.html" %}

{% block title %}Contact{% endblock %}

{% block body %}
    <h1>The Contact Page</h1>
{% endblock %}

core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Welcome{% endblock %}

{% block body %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.images.url }}" class="rounded-t-xl"></img>
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                        
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>    
                </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block body %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{ item.image.url }}" class="rounded-xl">
        </div>
    </div>
{% endblock %}